export const INITIAL_STATE_CUSTOMER = {
  id: "",
  nome: "",
  cpfCnpj: "",
  ie: "",
  im: "",
  nif: "",
  endereco: "",
  numero: "",
  complemento: "",
  bairro: "",
  cidade: "",
  uf: "",
  cep: "",
  telefone: "",
  celular: "",
  email: "",
  dataNascimento: "",
  observacao: "",
  consumidor_final: 1,
  contribuinte: 9,
}
